### ISSUE TITLE
Even python-pypdf2 is installed, I still get error messages in Manjaro

### ISSUE THREAD

**Issue by lobaluna** [arminstraub/krop#28]
Hi,

I installed from AUR using yay in Manjaro.
This is the output that I get:

```
$ krop

(python:9314): Gtk-WARNING **: 22:00:05.427: Unable to locate theme engine in module_path: "clearlooks",

(python:9314): Gtk-WARNING **: 22:00:05.428: Unable to locate theme engine in module_path: "clearlooks",
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/krop/pdfcropper.py", line 28, in <module>
    from pyPdf import PdfFileReader, PdfFileWriter
ModuleNotFoundError: No module named 'pyPdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/krop", line 33, in <module>
    sys.exit(load_entry_point('krop', 'console_scripts', 'krop')())
  File "/usr/lib/python3.10/site-packages/krop/application.py", line 81, in main
    from krop.mainwindow import MainWindow
  File "/usr/lib/python3.10/site-packages/krop/mainwindow.py", line 46, in <module>
    from krop.pdfcropper import PdfFile, PdfCropper, PdfEncryptedError, optimizePdfGhostscript
  File "/usr/lib/python3.10/site-packages/krop/pdfcropper.py", line 34, in <module>
    raise RuntimeError(_msg)
RuntimeError: Please install PyPDF2 (or its predecessor pyPdf) first.
	On recent versions of Ubuntu, the following should do the trick:
	sudo apt-get install python-pypdf2
	(or, if using python3) sudo apt-get install python3-pypdf2
```

I am totally sure that python-pypdf2 is installed:

```
$ yay -Ss python-pypdf
aur/python-pypdf3 1.0.5-1 (+0 0.00) 
    Pure-Python PDF library for splitting, merging, cropping, and transforming PDF pages.
aur/python-pypdf2-git b17382f-1 (+5 0.00) 
    PyPDF2 library for Python3
aur/python-pypdf2 1.26.0-2 (+20 1.23) (Installed)
    A utility to read and write PDFs with Python
```

Is there a workaround, something like softlinking to the already installed library?

**Comment by lobaluna** [comment]
Problem solved: 

I change to python-pypdf2-git and then krop opened.

**Comment by arminstraub** [comment]
Thank you for the update!  I am glad you got things to work!
